extends Node
class_name Sound

## The machine's noises.
##
## Every sample is generated by tools/make_sounds.py out of arithmetic - a few
## decaying sinusoids and some filtered noise - rather than downloaded. That is
## partly so the rights are unambiguous in something that is sold, and partly
## because these particular sounds are what modal synthesis is for: a keyboard
## is a switch, a keycap and a plate, all ringing at once and dying away at
## different rates.
##
## Reached through statics - Sound.key_down(), Sound.passed() - because the
## things that make noise are scattered across the launcher and threading a
## reference to every one of them would be worse than one well-known name.
## Nothing here is required: with the node absent or the sound off, every call
## is a no-op and the launcher behaves exactly as it did before.

const DIR := "res://audio/"

## One player per overlapping sound. Typing at speed is the case that decides
## this: at 8 characters a second with a 90ms sample, three can be sounding at
## once, and a single player would cut each one off at the next keystroke -
## which is audibly a machine gun rather than a keyboard.
const VOICES := 10

## Set once, in _ready. The launcher has exactly one of these.
static var instance: Sound = null

## Per-sound level, in decibels, applied on top of the master. These are the
## mix: clicks sit under speech, the room sits under everything, and the PC
## speaker is loud because a PC speaker was.
const LEVEL := {
	"key": -14.0,
	"key_up": -20.0,
	"key_space": -15.0,
	"mouse_down": -15.0,
	"mouse_up": -21.0,
	"ui_click": -17.0,
	"boot": -11.0,
	"passed": -10.0,
	"failed": -12.0,
	"error": -13.0,
}

## The room, which is quieter than anything else by a long way. It is meant to
## be noticed when it stops rather than while it runs.
const ROOM_DB := -27.0

var _bank: Dictionary = {}
var _voices: Array[AudioStreamPlayer] = []
var _next := 0
var _room: AudioStreamPlayer = null
var _keys: Array[AudioStream] = []
var _key_ups: Array[AudioStream] = []
var _key_n := 0
var enabled := true


func _ready() -> void:
	instance = self
	for i in VOICES:
		var p := AudioStreamPlayer.new()
		p.bus = "Master"
		add_child(p)
		_voices.append(p)

	for n: String in LEVEL:
		_load(n)
	for i in 6:
		var k := _load("key_%d" % i)
		if k != null:
			_keys.append(k)
		var u := _load("key_up_%d" % i)
		if u != null:
			_key_ups.append(u)

	var room_stream := _load("room")
	if room_stream != null:
		# Looping is set here rather than in the import settings so the file on
		# disk stays a plain wav that any tool can open. make_sounds.py folds
		# the noise tail back over its head, so the join is quieter than an
		# ordinary step between two samples and needs no fade.
		if room_stream is AudioStreamWAV:
			var w := room_stream as AudioStreamWAV
			w.loop_mode = AudioStreamWAV.LOOP_FORWARD
			w.loop_begin = 0
			# Counted rather than left at zero. A loop that quietly plays once
			# and stops is the kind of bug nobody files: the room goes away and
			# the player thinks they imagined it.
			var bytes_per_frame := (2 if w.format == AudioStreamWAV.FORMAT_16_BITS else 1)
			if w.stereo:
				bytes_per_frame *= 2
			w.loop_end = w.data.size() / bytes_per_frame
		_room = AudioStreamPlayer.new()
		_room.stream = room_stream
		_room.volume_db = ROOM_DB
		_room.bus = "Master"
		# If this ever fires, the loop did not take and the room has gone
		# silent. It is the only way to notice from outside.
		_room.finished.connect(func() -> void:
			push_warning("room tone stopped; the loop is not set"))
		add_child(_room)


func _load(name: String) -> AudioStream:
	var path := DIR + name + ".wav"
	if not ResourceLoader.exists(path):
		return null
	var s: AudioStream = load(path)
	_bank[name] = s
	return s


## Start the room tone. Called when the guest is actually up, so that silence
## before then reads as a machine that is not on yet.
static func room_on() -> void:
	if instance != null and instance.enabled and instance._room != null:
		instance._room.play()


static func room_off() -> void:
	if instance != null and instance._room != null:
		instance._room.stop()


static func set_enabled(on: bool) -> void:
	if instance == null:
		return
	instance.enabled = on
	if instance._room != null:
		if on:
			instance._room.play()
		else:
			instance._room.stop()


static func is_enabled() -> bool:
	return instance != null and instance.enabled


## One sound, on the next free voice.
##
## Round robin rather than looking for an idle player: the oldest voice is the
## one most likely to have finished, and with ten of them a sound has a full
## second before its turn comes round again.
static func play(name: String, pitch: float = 1.0) -> void:
	var s := instance
	if s == null or not s.enabled or not s._bank.has(name):
		return
	var p := s._voices[s._next]
	s._next = (s._next + 1) % VOICES
	p.stream = s._bank[name]
	p.volume_db = LEVEL.get(name, -12.0)
	p.pitch_scale = pitch
	p.play()


## A key going down. Six samples in rotation, each a slightly different board.
##
## The rotation is deliberate rather than random: a random pick repeats itself
## audibly about a sixth of the time, and two identical clicks in a row is the
## thing that gives a synthesised keyboard away.
static func key_down(is_space: bool = false) -> void:
	var s := instance
	if s == null or not s.enabled:
		return
	if is_space:
		play("key_space", randf_range(0.97, 1.03))
		return
	if s._keys.is_empty():
		return
	var p := s._voices[s._next]
	s._next = (s._next + 1) % VOICES
	p.stream = s._keys[s._key_n]
	s._key_n = (s._key_n + 1) % s._keys.size()
	p.volume_db = LEVEL["key"]
	# A few percent either way on top of the six variants. Real keys differ
	# from each other and from themselves; this is cheap and does the rest.
	p.pitch_scale = randf_range(0.94, 1.06)
	p.play()


static func key_up() -> void:
	var s := instance
	if s == null or not s.enabled or s._key_ups.is_empty():
		return
	var p := s._voices[s._next]
	s._next = (s._next + 1) % VOICES
	p.stream = s._key_ups[s._key_n % s._key_ups.size()]
	p.volume_db = LEVEL["key_up"]
	p.pitch_scale = randf_range(0.94, 1.06)
	p.play()


static func mouse_down() -> void:
	play("mouse_down", randf_range(0.97, 1.03))


static func mouse_up() -> void:
	play("mouse_up", randf_range(0.97, 1.03))


static func ui_click() -> void:
	play("ui_click", randf_range(0.97, 1.03))


static func boot() -> void:
	play("boot")


static func passed() -> void:
	play("passed")


static func failed() -> void:
	play("failed")


static func error() -> void:
	play("error")
